import type { IconType } from "react-icons";
import {
  HiOutlineHome,
  HiOutlineHashtag,
  HiOutlineChatBubbleLeftRight,
  HiOutlineInbox,
  HiOutlineVideoCamera,
  HiOutlineVideoCameraSlash,
  HiOutlineCalendarDays,
  HiOutlineUsers,
  HiOutlineCog6Tooth,
  HiOutlinePhone,
  HiOutlinePhoneArrowDownLeft,
  HiOutlineSparkles,
  HiOutlineCheck,
  HiOutlineCheckCircle,
  HiOutlineArrowRight,
  HiOutlineChevronUpDown,
  HiOutlineMagnifyingGlass,
  HiOutlinePlus,
  HiOutlineClock,
  HiOutlineSquares2X2,
  HiOutlineBars3,
  HiOutlineBell,
  HiOutlineXMark,
  HiOutlineKey,
  HiOutlineLink,
  HiOutlineClipboard,
  HiOutlineTrash,
  HiOutlineMicrophone,
  HiOutlinePaperAirplane,
  HiPlay,
  HiOutlineHandThumbUp,
  HiOutlineChatBubbleOvalLeft,
  HiOutlinePresentationChartBar,
  HiOutlineGlobeAlt,
  HiOutlineCurrencyDollar,
  HiOutlineChevronRight,
  HiOutlineChevronLeft,
  HiOutlineChevronDown,
  HiOutlineComputerDesktop,
  HiOutlineHandRaised,
  HiOutlineFaceSmile,
  HiOutlineLanguage,
  HiOutlineArrowRightOnRectangle,
  HiOutlineSpeakerWave,
  HiOutlineSpeakerXMark,
  HiOutlineInformationCircle,
  HiOutlineEllipsisVertical,
  HiOutlineUserMinus,
  HiOutlineUserPlus,
  HiOutlineStar,
  HiOutlinePhoneXMark,
  HiOutlineChatBubbleBottomCenterText,
  HiOutlinePaperClip,
  HiOutlinePencilSquare,
  HiOutlineEllipsisHorizontal,
  HiOutlineTag,
  HiOutlinePhoto,
  HiOutlineTv,
  HiOutlineSignal,
  HiOutlineUserGroup,
  HiOutlineAdjustmentsHorizontal,
  HiOutlineClipboardDocumentList,
  HiOutlineFilm,
  HiOutlineChartBar,
  HiOutlineTicket,
  HiOutlineIdentification,
  HiOutlinePrinter,
  HiOutlineExclamationTriangle,
  HiOutlineQuestionMarkCircle,
  HiOutlineArrowTopRightOnSquare,
  HiOutlineArrowUp,
  HiOutlineUserCircle,
  HiOutlineBuildingOffice2,
  HiOutlineMapPin,
  HiOutlineArrowDownTray,
  HiOutlineArrowPath,
  HiOutlineBellAlert,
  HiOutlineEnvelope,
  HiOutlineFlag,
  HiOutlineBolt,
  HiOutlineExclamationCircle,
} from "react-icons/hi2";

/**
 * Heroicons v2 (Flowbite'ın kullandığı set) üzerine ince sarmalayıcı.
 * Kullanım: <Icon name="home" className="w-5 h-5" />
 * Yeni ikon gerekirse react-icons/hi2'den import edip MAP'e ekle.
 */
const MAP: Record<string, IconType> = {
  home: HiOutlineHome,
  hash: HiOutlineHashtag,
  chat: HiOutlineChatBubbleLeftRight,
  inbox: HiOutlineInbox,
  video: HiOutlineVideoCamera,
  videoOff: HiOutlineVideoCameraSlash,
  calendar: HiOutlineCalendarDays,
  calCheck: HiOutlineCalendarDays,
  users: HiOutlineUsers,
  settings: HiOutlineCog6Tooth,
  phone: HiOutlinePhone,
  voicemail: HiOutlinePhoneArrowDownLeft,
  sparkles: HiOutlineSparkles,
  check: HiOutlineCheck,
  checkCircle: HiOutlineCheckCircle,
  arrow: HiOutlineArrowRight,
  selector: HiOutlineChevronUpDown,
  search: HiOutlineMagnifyingGlass,
  plus: HiOutlinePlus,
  clock: HiOutlineClock,
  grid: HiOutlineSquares2X2,
  menu: HiOutlineBars3,
  bell: HiOutlineBell,
  close: HiOutlineXMark,
  key: HiOutlineKey,
  link: HiOutlineLink,
  copy: HiOutlineClipboard,
  trash: HiOutlineTrash,
  mic: HiOutlineMicrophone,
  send: HiOutlinePaperAirplane,
  play: HiPlay,
  thumb: HiOutlineHandThumbUp,
  comment: HiOutlineChatBubbleOvalLeft,
  webinar: HiOutlinePresentationChartBar,
  globe: HiOutlineGlobeAlt,
  money: HiOutlineCurrencyDollar,
  chevronRight: HiOutlineChevronRight,
  chevronLeft: HiOutlineChevronLeft,
  chevronDown: HiOutlineChevronDown,
  screen: HiOutlineComputerDesktop,
  handRaised: HiOutlineHandRaised,
  smile: HiOutlineFaceSmile,
  cc: HiOutlineLanguage,
  logout: HiOutlineArrowRightOnRectangle,
  volume: HiOutlineSpeakerWave,
  volumeOff: HiOutlineSpeakerXMark,
  info: HiOutlineInformationCircle,
  ellipsis: HiOutlineEllipsisVertical,
  userMinus: HiOutlineUserMinus,
  userPlus: HiOutlineUserPlus,
  star: HiOutlineStar,
  phoneDecline: HiOutlinePhoneXMark,
  micOff: HiOutlineSpeakerXMark,
  message: HiOutlineChatBubbleBottomCenterText,
  paperclip: HiOutlinePaperClip,
  pencil: HiOutlinePencilSquare,
  ellipsisH: HiOutlineEllipsisHorizontal,
  tag: HiOutlineTag,
  photo: HiOutlinePhoto,
  tv: HiOutlineTv,
  monitor: HiOutlineComputerDesktop,
  broadcast: HiOutlineSignal,
  usersThree: HiOutlineUserGroup,
  sliders: HiOutlineAdjustmentsHorizontal,
  clipboard: HiOutlineClipboardDocumentList,
  film: HiOutlineFilm,
  chartBar: HiOutlineChartBar,
  ticket: HiOutlineTicket,
  identification: HiOutlineIdentification,
  printer: HiOutlinePrinter,
  warning: HiOutlineExclamationTriangle,
  question: HiOutlineQuestionMarkCircle,
  thumbUp: HiOutlineHandThumbUp,
  externalLink: HiOutlineArrowTopRightOnSquare,
  signOut: HiOutlineArrowRightOnRectangle,
  arrowUp: HiOutlineArrowUp,
  userCircle: HiOutlineUserCircle,
  captions: HiOutlineChatBubbleBottomCenterText,
  desk: HiOutlineBuildingOffice2,
  room: HiOutlineBuildingOffice2,
  pin: HiOutlineMapPin,
  download: HiOutlineArrowDownTray,
  reschedule: HiOutlineArrowPath,
  reminder: HiOutlineBellAlert,
  envelope: HiOutlineEnvelope,
  flag: HiOutlineFlag,
  bolt: HiOutlineBolt,
  alert: HiOutlineExclamationCircle,
};

export type IconName = keyof typeof MAP;

interface IconProps {
  name: string;
  className?: string;
}

export function Icon({ name, className }: IconProps) {
  const Cmp = MAP[name] ?? HiOutlineSquares2X2;
  return <Cmp className={className ?? "w-5 h-5"} aria-hidden />;
}
